spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_api_db
    username: SEgroup
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret-key: "60429fb4f4e23a0fa7ed9c6cf5823a57a4a2abc497732d3db7f3fbc0930aa14e"

